# Generated by Django 4.0.2 on 2022-08-20 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user_subscriptions',
            field=models.ManyToManyField(related_name='user_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
