# Generated by Django 4.0.2 on 2022-08-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_subscriptions_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-create_date'], 'permissions': (('can_manage_subscriptions', 'Can manage subscriptions'),), 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
