# Generated by Django 4.0.2 on 2022-08-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='members',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
