# Generated by Django 4.0.2 on 2022-08-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscriptions_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='members',
            new_name='subscriptions',
        ),
    ]
