# Generated by Django 4.0.2 on 2022-08-27 01:46

import apps.core.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_account_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_expiry',
            field=models.DateTimeField(default=apps.core.users.models.get_profile_expiry),
        ),
    ]
