# Generated by Django 4.0.2 on 2022-08-20 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription_access', models.ManyToManyField(to='users.Subscriptions')),
            ],
            options={
                'verbose_name_plural': 'File Sets',
                'ordering': ['-create_date'],
                'permissions': (('can_merge_sets', 'Can merge sets'),),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='file 1', max_length=999)),
                ('file_type', models.CharField(default='binary', max_length=999)),
                ('file_size', models.IntegerField(default=0)),
                ('location', models.FileField(upload_to='files')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_shareable', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('file_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.fileset')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['-create_date'],
            },
        ),
    ]
