# Generated by Django 4.0.2 on 2022-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('files', '0002_alter_fileset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='subscription_access',
            field=models.ManyToManyField(null=True, to='users.Subscriptions'),
        ),
    ]
