# Generated by Django 4.0.2 on 2022-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
