# Generated by Django 4.0.2 on 2022-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('files', '0003_alter_fileset_subscription_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='subscription_access',
            field=models.ManyToManyField(to='users.Subscriptions'),
        ),
    ]
