# Generated by Django 4.0.2 on 2022-08-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_subscriptions'),
        ('files', '0003_files_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('group_access', models.ManyToManyField(to='users.Subscriptions')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'File Sets',
                'ordering': ['-create_date'],
                'permissions': (('can_merge_sets', 'Can merge sets'),),
            },
        ),
        migrations.AddField(
            model_name='files',
            name='file_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.fileset'),
        ),
    ]
