# Generated by Django 4.0.2 on 2022-08-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_files_owner_fileset_files_file_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileset',
            old_name='group_access',
            new_name='subscription_access',
        ),
    ]
