# Generated by Django 4.0.2 on 2022-08-24 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0007_remove_fileset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='moderators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
