# Generated by Django 4.0.2 on 2022-08-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_fileset_moderators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileset',
            options={'ordering': ['-create_date'], 'permissions': (('can_merge_sets', 'Can merge sets'), ('can_moderate_files', 'Can moderate files')), 'verbose_name_plural': 'File Sets'},
        ),
    ]
