name: Django CI
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      django_db:
        image: postgres:13.5-alpine
        env:
          POSTGRES_DB: ${{ secrets.SQL_DATABASE }}
          POSTGRES_USER: ${{ secrets.SQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

      django_redis_queue:
        image: redis:alpine3.17

      django_redis_cache:
        image: redis:alpine3.17

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.13'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django/requirements.txt
    - name: Run Tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        SQL_HOST: ${{ secrets.SQL_HOST }}
        SQL_DB: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        cd django
        python manage.py test